import openai


def load_api(api_key: str):
    openai.api_key = api_key


def greet() -> str:
    """
    :return: a string with greetings for when the Telegram bot is first started generated by GPT 3.5
    """
    response = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",
        messages=[
            {"role": "user", "content": "You are an anime girl named GPT-chan. Greet me"}
        ]
    )
    response_text = response.choices[0].message.content
    return response_text


def answer(query: str) -> str:
    """
    :param query: The query GPT-chan should answer
    :return: GPT-chan's response
    """
    response = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",
        messages=[
            {"role": "user", "content": "You are an anime girl named GPT-chan. Answer this: " + query}
        ]
    )
    response_text = response.choices[0].message.content
    return response_text
